# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`
version: '3.9'

services:
  app:
   image: registry.lts.harvard.edu/lts/transfer-service-snapshot:deedee
   build:
     context: .
     dockerfile: Dockerfile

